spring:
  application:
    name: productApi

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

  health:
    redis:
      enabled: true