spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-60a102a-mogros-83f2.e.aivencloud.com:12566/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_Vl2ITtuLt0-QSr23AeL

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: redis-19353.c251.east-us-mz.azure.cloud.redislabs.com
      port: 19353
      username: default
      password: aZGi0FnwXndgWTIyUoXNivxwX9DifB71

  cache:
    type: redis

  mongodb:
    uri: mongodb+srv://mogros_db_user:9sEiqF04VzenfL0s@cluster0.t0wpwn7.mongodb.net/?appName=Cluster0
    database: ProductDB-Auditoria

